### ISSUE TITLE
Failed to decode binary data

### ISSUE THREAD

**Issue by PhilippeGouin** [umeat/unlzw#1]
Hello,

thanks for this function as it is really sad to not be able to decode old .Z files in python.

It works fine, I've just had a problem with the last line which decode the bytearray to a unicode: my uncompressed data are binaries and can't be decoded to strings.
For my convenience I just changed:
-    return bytearray(put).decode("utf-8")
-    return bytearray(put)

but it could be better to add an argument to the function, something like:
unlzw(data, format='byte'|'unicode'):
    ...

**Comment by umeat** [comment]
Thanks for raising this issue.

I've tried to address this by changing the return to: return bytes(bytearray(put))

The output is actually the same as when using decode('utf-8') for strings which _can_ be decoded as utf-8.

This should fix the issue you are seeing.

**Comment by PhilippeGouin** [comment]
Works fine !
