### ISSUE TITLE
create 0.1.0 release tag

### ISSUE THREAD

**Issue by tomkralidis** [umeat/unlzw#4]
Per subject, any chance a release 0.1.0 tag can be created?  This will help (us at least) pin to a release for our debian package setup.  `unlzw/__init__.py`'s `__version__` parameter and `debian/changelog` are both ready/pinned to 0.1.0 (note these two files need to be updated as part of future releases).

**Comment by tomkralidis** [comment]
Gentle bump, cheers.

**Comment by umeat** [comment]
Yeah, sorry. I had completely forgotten about this repo. I'll get to it asap.
